# Generated by Django 5.2.8 on 2025-11-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کد یکتا برای مکان', max_length=50, unique=True, verbose_name='کد')),
                ('title', models.CharField(help_text='نام مکان', max_length=50, verbose_name='عنوان')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='places/main_image')),
                ('visiting_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعت بازدید')),
                ('open_days', models.CharField(blank=True, choices=[('mon', 'دوشنبه'), ('tue', 'سه\u200cشنبه'), ('wed', 'چهارشنبه'), ('thu', 'پنج\u200cشنبه'), ('fri', 'جمعه'), ('sat', 'شنبه'), ('sun', 'یک\u200cشنبه')], max_length=100, null=True, verbose_name='روز بازدید')),
                ('regulations', models.TextField(blank=True, help_text='فوانین و مقررات', null=True, verbose_name='قوانین')),
                ('more_info', models.TextField(blank=True, help_text='اطلاعت بیشتر', null=True, verbose_name='اطلاعات بیشتر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت مکان')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کد یکتا برای گروه', max_length=50, unique=True, verbose_name='کد ')),
                ('title', models.CharField(choices=[('1', 'عمومی'), ('2', 'گروهی'), ('3', 'دانشجویی'), ('4', 'خارجی')], default='1', max_length=10, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کد یکتا برای بلیط', max_length=50, unique=True, verbose_name='کد')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_price', to='introduction.place')),
                ('visitor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_price', to='introduction.visitor_group')),
            ],
        ),
    ]
